name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - dev  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud with Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/YOUR_POOL_ID/providers/YOUR_PROVIDER_ID
        service_account: YOUR_SERVICE_ACCOUNT@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    - name: Build Docker image
      run: |
        IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:${GITHUB_SHA}
        docker build -t $IMAGE_TAG .
        
    - name: Push Docker image to Google Container Registry (GCR)
      run: |
        IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:${GITHUB_SHA}
        docker push $IMAGE_TAG

    - name: Deploy to Cloud Run
      run: |
        IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:${GITHUB_SHA}
        gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
          --image $IMAGE_TAG \
          --platform managed \
          --region YOUR_REGION \
          --allow-unauthenticated
